server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3 #3秒返回数据
  servlet:
    multipart:
      max-file-size: 10MB #单个文件为10MB
      max-request-size: 100MB # 最大档次请求为100MB